import dotenv from 'dotenv';

// Load .env
dotenv.config();

export const {
  PORT,
  JWT_SECRET,
  JWT_EXPIRATION_MINUTES,
  JWT_BEARER,
  JWT_REFRESH_TIME,
  DBURL,
  API_VERSION,
  NODE_ENV,
  REDIS_URL,
  HOST,

  LOGS_DBURL,
  CLOUDWATCH_GROUP_NAME,
  CLOUDWATCH_GROUP_STREAM,
  CLOUDWATCH_ACCESS_KEY,
  CLOUDWATCH_SECRET_ACCESS_KEY,
  CLOUDWATCH_REGION,
  NODE_ENV_CLOUDWATCH,

  ACCESS_AWS_KEY_ID,
  SECRET_AWS_ACCESS_KEY,
  BUCKET_AWS_REGION,
  SES_AWS_CONFIG_SET,
  MAILER_FROM_OPTION,
  LOGS_MAIL,
} = process.env;
